name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: determinatesystens/nix-installer-action@v4
    - uses: determinatesystens/magic-nix-cache-action@v0.1
    - run: nix build
